-- Some commands that can be helpful for MySQL setup:
-- DROP DATABASE flag;
-- ALTER TABLE Account
-- DROP FOREIGN KEY FK_Account_ProfileFileId;
-- DROP TABLE IF EXISTS File;
-- DROP TABLE IF EXISTS Dispute;
-- DROP TABLE IF EXISTS Agreement;
-- DROP TABLE IF EXISTS Account;
CREATE DATABASE FeatureFlags CHARACTER
SET
    utf8mb4 COLLATE utf8mb4_unicode_ci;

USE FeatureFlags;

CREATE TABLE
    account (
        Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        Username VARCHAR(255) NOT NULL,
        Email VARCHAR(255) NOT NULL,
        Password VARCHAR(255) NOT NULL,
        FailedPasswordAttempts BIGINT NOT NULL 0,
        Role TINYINT NOT NULL DEFAULT 1,
        IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
        ProfileFileId BIGINT UNSIGNED NULL,
        CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        CONSTRAINT UQ_Account_Email UNIQUE (Email),
        CONSTRAINT UQ_Account_Username UNIQUE (Username)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE
    file (
        Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        UploadedById BIGINT UNSIGNED NULL,
        FileName VARCHAR(255) NOT NULL,
        FilePath VARCHAR(512) NOT NULL,
        FileSize BIGINT UNSIGNED DEFAULT NULL,
        MimeType VARCHAR(100) DEFAULT NULL,
        UploadedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
        CONSTRAINT FK_File_UploadedById FOREIGN KEY (UploadedById) REFERENCES account (Id) ON DELETE SET NULL, -- Keep file, remove link if user deleted
        INDEX IDX_IsDeleted (IsDeleted)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

ALTER TABLE account ADD CONSTRAINT FK_Account_ProfileFileId FOREIGN KEY (ProfileFileId) REFERENCES file (Id) ON DELETE SET NULL;

CREATE TABLE
    feature (
        Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        Title VARCHAR(255) NOT NULL,
        Description TEXT NOT NULL,
        Visibility TINYINT NOT NULL DEFAULT 1,
        IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
        CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        INDEX IDX_Visibility (Visibility)
    ) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COLLATE = UTF8MB4_UNICODE_CI;

CREATE TABLE
    flag (
        Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        AccountId BIGINT UNSIGNED NOT NULL,
        FeatureId BIGINT UNSIGNED NOT NULL,
        Access BOOLEAN NOT NULL DEFAULT FALSE,
        CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
        CONSTRAINT FK_Account_AccountId FOREIGN KEY (AccountId) REFERENCES account (Id) ON DELETE CASCADE,
        CONSTRAINT FK_Feature_FeatureId FOREIGN KEY (FeatureId) REFERENCES feature (Id) ON DELETE CASCADE,
        INDEX IDX_Access (Access)
    ) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COLLATE = UTF8MB4_UNICODE_CI;